### ISSUE TITLE
Feature request: custom power state sensor for media_player

### ISSUE THREAD

**Issue by FezVrasta** [vpnmaster/homeassistant-custom-components#101]
I have a custom sensor I use to track the state of my TV (it fetches a REST API exposed by the TV), I'd like to be able to use it to tell the broadlink media_player component the state of my TV.

**Comment by cubilon** [comment]
+1

**Comment by vpnmaster** [comment]
Hello,
What is the output of your sensor?

**Comment by cubilon** [comment]
on/off

**Comment by vpnmaster** [comment]
I’m planning to refactor power_consumption_entity and power_consumption_threshold in order to accepts true/false values.
For the moment you can implement a template sensor.

**Comment by cubilon** [comment]
great. keep in mind power consumption is not the only possible way to determine the state,
so a template sensor will be forever useful.

PS will this future feature (and the template senso top) good for climates and fans too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cubilon** [comment]
I removed my previous comment, I didn’t get what you mean.

Ok great: you’re gonna change the way power_consumption_entity works and letting on/off values to be understood.

Btw, why don’t you configure the same parameter in climate/fan code? this could be really useful for setting those kind of entries’ state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpnmaster** [comment]
It is implemented in the new versions. Thank you
