### ISSUE TITLE
Emulated Hue integration

### ISSUE THREAD

**Issue by km2000us** [vpnmaster/homeassistant-custom-components#110]
Thanks for the great custom component.

I was wondering if it is possible to expose this and control the air-conditioner using Alexa.  I have managed to expose the 'climate' domain and the relevant entities - 'climate.living_room_ac'.  But spoken commands to Alexa are registered but not executed, eg. "Alexa, turn on Living Room AC" (which is the set friendly name).  Any help would appreciated.

**Comment by vpnmaster** [comment]
I’m not sure if it is working with emulated hue. Please try with the last version where on/off support added
