### ISSUE TITLE
error using a climate service

### ISSUE THREAD

**Issue by juancarloscastro75** [vpnmaster/homeassistant-custom-components#113]
Hello

I'm using your climate component, and the truth is that it works wonders.
But nevertheless, I have a problem: I want to be able to control my climate through scripts. automations, etc ... and I do not get it.

If I try to turn off the ac directly using the service from the developer tools, I get an error:
![image](https://user-images.githubusercontent.com/45803748/52527596-b8af7300-2ccb-11e9-93ae-01b25b637909.png)

> Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 506, in turn_off
    raise NotImplementedError()
NotImplementedError

Would there be possibility to control the climate through service?
`
script:
  ac_off:
    sequence:
      - service: climate.turn_off
        data:
          entity_id: climate.aa_comedor
  ac_hot:
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.aa_comedor
          operation_mode: hot
          temperature: 23
          fan_mode: high
  ac_cool:
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.aa_comedor
          operation_mode: cool
          temperature: 28
          fan_mode: high
`

**Comment by vpnmaster** [comment]
Hi,
In order to turn off the device through service please set the operation mode to off.

```
{
  "entity_id": "climate.office_ac",
  "operation_mode": "Off"
}
```

**Comment by juancarloscastro75** [comment]
Hi,

Thanks for your help, bur the error remains:
![image](https://user-images.githubusercontent.com/45803748/52531651-d0f9af00-2d18-11e9-867d-f51612df1654.png)

Now, there is not an error on the log, but.... nothing happens
I have watched the broadlink, and it does not emit IR.

Regards

**Comment by vpnmaster** [comment]
Please change Sevicio to climate.set_operation_mode

**Comment by juancarloscastro75** [comment]
YES, now works

Now I will test the script.
Thank you

**Comment by juancarloscastro75** [comment]
Hi,

Then, I must use this script:
  ac_heat:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: heat
      - delay: '00:00:01'
      - service: climate.set_temperature
        data:
          entity_id: climate.aa_comedor
          temperature: "23"
      - delay: '00:00:01'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.aa_comedor
          fan_mode: high
      - service: notify.administrador
        data:
          message: "script ac_heat"
  ac_cool:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: cool
      - delay: '00:00:01'
      - service: climate.set_temperature
        data:
          entity_id: climate.aa_comedor
          temperature: "28"
      - delay: '00:00:01'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.aa_comedor
          fan_mode: high
      - service: notify.administrador
        data:
          message: "script ac_cool"

Is it necessary to send all three orders? Can not everything be done in a single order?

Again, thank you very much

**Comment by vpnmaster** [comment]
No, you can't. I suggest you call climate.set_operation_mode at the end of the sequence.

**Comment by juancarloscastro75** [comment]
Thanks

Then, I am using this code:
`  ac_cool:
    sequence:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.aa_comedor
          operation_mode: cool
      - delay: '00:00:01'
      - service: climate.set_temperature
        data:
          entity_id: climate.aa_comedor
          temperature: "28"
      - delay: '00:00:01'
      - service: climate.set_fan_mode
        data:
          entity_id: climate.aa_comedor
          fan_mode: high`

Thanks
