### ISSUE TITLE
Problem with last version of media_player

### ISSUE THREAD

**Issue by cubilon** [vpnmaster/homeassistant-custom-components#120]
At boot I find this:

> Feb 17 17:56:44 raspberrypi hass[24506]: 2019-02-17 17:56:44 ERROR (MainThread) [homeassistant.loader] Unable to find platform broadlink
> Feb 17 17:56:44 raspberrypi hass[24506]: 2019-02-17 17:56:44 INFO (MainThread) [homeassistant.loader] Loaded media_player.braviatv from homeassistant.components.media_player.braviatv
> Feb 17 17:56:44 raspberrypi hass[24506]: 2019-02-17 17:56:44 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.media_player.broadlink. Make sure all dependencies are installed
> Feb 17 17:56:44 raspberrypi hass[24506]: Traceback (most recent call last):
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 117, in _load_file
> Feb 17 17:56:44 raspberrypi hass[24506]:     module = importlib.import_module(path)
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
> Feb 17 17:56:44 raspberrypi hass[24506]:     return _bootstrap._gcd_import(name[level:], package, level)
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
> Feb 17 17:56:44 raspberrypi hass[24506]:   File "/home/homeassistant/.homeassistant/custom_components/media_player/broadlink.py", line 15, in <module>
> Feb 17 17:56:44 raspberrypi hass[24506]:     from homeassistant.components.media_player.const import (
> Feb 17 17:56:44 raspberrypi hass[24506]: ImportError: No module named 'homeassistant.components.media_player.const'
> Feb 17 17:56:44 raspberrypi hass[24506]: 2019-02-17 17:56:44 ERROR (MainThread) [homeassistant.loader] Unable to find platform broadlink

Using the previous .py, everythings is ok.
Running on Raspbian HA 0.87.x

**Comment by madrose** [comment]
I have exactly the same issue

**Comment by smartHomeHub** [comment]
Hi,
Sorry for the inconvenience. The latest version is compatible with the HA release that will be released on Wednesday.

**Comment by acidquest** [comment]
i have last version of HA (0.87.1) and i have error with last version broadlink media player

**Comment by cubilon** [comment]
great, thx Vassilis

**Comment by niccolobusato** [comment]
has been updated?

**Comment by cubilon** [comment]
HA? yep, 0.88 is out
