### ISSUE TITLE
Humidity sensor

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [vpnmaster/homeassistant-custom-components#16]
Not really an issue, but can we integrate a humidity sensor into the Broadlink climate component?

These custom_components work great on the latest version of HA dev btw...

**Comment by vpnmaster** [comment]
No, sorry. This component follows the universal rules of the climate component, so humidity value not exists.
You can try home assistant custom UI in order to accomplish your task.
https://github.com/andrey-git/home-assistant-custom-ui
Thank you
