### ISSUE TITLE
Errors with latest dev

### ISSUE THREAD

**Issue by mouth4war** [vpnmaster/homeassistant-custom-components#21]
2018-02-20 17:22:14 ERROR (MainThread) [homeassistant.co
nfig] Invalid config for [climate.broadlink]: string val
ue is None for dictionary value @ data['default_operatio
n_from_idle']. Got None. (See ?, line ?). Please check t
he docs at https://home-assistant.io/components/climate.
broadlink/                                              
2018-02-20 17:22:15 ERROR (MainThread) [homeassistant.co
nfig] Invalid config for [media_player.broadlink]: strin
g value is None for dictionary value @ data['ping_host']
. Got None                                              
string value is None for dictionary value @ data['power_
consumption_entity']. Got None. (See ?, line ?). Please 
check the docs at https://home-assistant.io/components/m
edia_player.broadlink/                                  
2018-02-20 17:22:15 ERROR (MainThread) [homeassistant.co
nfig] Invalid config for [media_player.broadlink]: strin
g value is None for dictionary value @ data['ping_host']
. Got None                                              
string value is None for dictionary value @ data['power_
consumption_entity']. Got None. (See ?, line ?). Please 
check the docs at https://home-assistant.io/components/m
edia_player.broadlink/

**Comment by mouth4war** [comment]
Looks like HASS doesn't like the default value of None

**Comment by vpnmaster** [comment]
Hello, it seems a breaking change for 0.64.
I have fixed it, but I will upload it when the new version is released.

**Comment by mouth4war** [comment]
@vpnmaster great! can the dev users get a pastebin or something in the meanwhile? Thanks!
