### ISSUE TITLE
Error climate.broadlink in 0.64.1

### ISSUE THREAD

**Issue by truongtvd** [vpnmaster/homeassistant-custom-components#24]
Error climate.broadlink in 0.64.1
<img width="387" alt="screen shot 2018-02-28 at 3 11 46 pm" src="https://user-images.githubusercontent.com/31237205/36778099-5cc0c852-1c9e-11e8-9a54-0ce0ebdbcc9a.png">

**Comment by ihuex** [comment]
same problem!

**Comment by ihuex** [comment]
ok. i do it,  in broadlink.py    keep   REQUIREMENTS = ['broadlink==0.5']  to  REQUIREMENTS = ['broadlink==0.5.1']  then  ok!!

**Comment by truongtvd** [comment]
thank men. I fixed it
