### ISSUE TITLE
string value is None for dictionary value

### ISSUE THREAD

**Issue by nmajin** [vpnmaster/homeassistant-custom-components#27]
I am thinking there is an issue with version 0.64.2 of HA

2018-03-03 20:43:52 ERROR (MainThread) [homeassistant.config] Invalid config for [media_player.broadlink]: string value is None for dictionary value @ data['power_consumption_entity']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/media_player.broadlink/

**Comment by vpnmaster** [comment]
Hi,
Did you update broadlink.py with the last revision?

**Comment by nmajin** [comment]
Yep, just actually tried with 0.64.3, same error.

**Comment by nmajin** [comment]
Sorry thought you meant to try the latest version 0.64.3. What revision are you on right now, this is the configuration:

REQUIREMENTS = ['broadlink==0.5']

**Comment by vpnmaster** [comment]
Please update the broadlink.py with the new file:
https://raw.githubusercontent.com/vpnmaster/homeassistant-custom-components/master/custom_components/media_player/broadlink.py

**Comment by nmajin** [comment]
np, will test this out now.

**Comment by nmajin** [comment]
Awesome, thanks for the help and quick response, should have checked if the code was updated first.
