### ISSUE TITLE
Restful API support

### ISSUE THREAD

**Issue by honcheng** [vpnmaster/homeassistant-custom-components#3]
Thanks for the custom components. I've tried it and it works very well from the Dashboard. 

How do I use Restful API to set temperatures with this component?

**Comment by vpnmaster** [comment]
Hello,
Thank you for trying this component.

You can use this command to set the temperature via the Rest API.

```
curl -X POST \
   -H "Content-Type: application/json" \
   -d '{"entity_id": "climate.office_ac", "temperature": "19"}' \
   http://192.168.1.74:8123/api/services/climate/set_temperature
```

**Comment by honcheng** [comment]
Thanks. I did. Looks like I may have misunderstood how it works. 

If my aircon is idle/off, setting temperature does not turn on the aircon even though I provide a operation_mode in the parameter to change it to 'cool'. It seems the library just ignore the parameter, even though it's only supposed to go for default is not provided. 

Can you support that? 

![screen shot 2017-10-05 at 11 14 34 am](https://user-images.githubusercontent.com/208827/31209563-57b18386-a9be-11e7-9448-a0c57fbfca41.png)

Thanks for the library. I've added support for my Mitsubishi Electric aircon. Will send a PR soon.

**Comment by vpnmaster** [comment]
I made some tests and seems that Home Assistant ignores operation_mode in set_temperature service. You can test it by yourself in the demo platform:

```
climate:
  - platform: demo
```

**Comment by honcheng** [comment]
![screen shot 2017-10-05 at 5 01 35 pm](https://user-images.githubusercontent.com/208827/31219104-e0275c7e-a9ee-11e7-8e22-3d7d4eeaa10a.png)

Oh. Thought it's related to the set_temperature method in this library ignoring operation_mode. Was going to try adding here myself. Didn't know that HA supposed to do something upstream.

**Comment by vpnmaster** [comment]
I made some changes. Please download the updated component, add 'default_operation_from_idle: cool' in your configuration and try to set the temperature from idle mode.

**Comment by honcheng** [comment]
Wonderful. That works. Nice workaround.
