### ISSUE TITLE
Feature : add more option

### ISSUE THREAD

**Issue by earth08** [vpnmaster/homeassistant-custom-components#48]
Is it possible to add more feature to control AC
like
1) air flow up/mid/down left/centre/right
2) auto 3d
3) turbomode
4) powerfull ac mode
5) quiet/economy mode
and same like others
please add these features, thanks

**Comment by newzealandpaul** [comment]
Does the project support swing (airflow direction) already?

**Comment by earth08** [comment]
no it doesnt,
only temperature
cooling mode and fan speed is available
