### ISSUE TITLE
Off/Idle command from iOS HomeKit

### ISSUE THREAD

**Issue by tatunts** [vpnmaster/homeassistant-custom-components#58]
Hello my friend! How are you?

Really sorry to bother you, but I think something is wrong here, maybe you can help me...

I've migrated from the addon Homebridge to the native HomeKit component on my Hassio yesterday. Everything seems to be working just fine, very fast, snappy and realiable, really enjoying it.

I've noticed that If I set the AC to inactive on the **iOS app**, the state of the climate becomes "off", instead of "idle" (actually this was happening with the addon as well, but have not affected me until now). Now with the native HomeKit component, the icon on the Home app keeps showing as the last operational state, heat or cool, for example, like this:

![image](https://user-images.githubusercontent.com/25224882/41615786-8ce27702-73d2-11e8-94a4-c6a87a4d5db0.png)

The operation mode one the Hassio shows a blank state, like this:

![image](https://user-images.githubusercontent.com/25224882/41615314-48a87d8a-73d1-11e8-9420-a94d1dbed777.png)

Here is the AC card:

![image](https://user-images.githubusercontent.com/25224882/41615480-c29fd138-73d1-11e8-9640-d686883aed98.png)

Now I have to go to the Hassio interface, change it to "idle" to see the AC icon on my iOS Home App as "inactive" or "off"...

Is it possible to set your custom component to receive this "off" state and interpret as "idle"? I think this will solve this problem.

Or am I doing something wrong here?

Really appreciate your help my friend!

Thanks!

**Comment by vpnmaster** [comment]
Hi! Could you try to replace idle with 'off' in your config?
customize:
      operations:
        - 'off'
        - cool
        - ....

**Comment by tatunts** [comment]
Hello again @vpnmaster!

Amazing! It worked!

At first, I've got this error:

```
Log Details (ERROR)
Wed Jun 20 2018 19:36:46 GMT-0300 (Horário Padrão de Brasília)

Error executing service <ServiceCall climate.set_operation_mode: operation_mode=False, entity_id=['climate.ar_condicionado_da_sala']>
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'false'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 399, in async_operation_set_service
    await climate.async_set_operation_mode(operation_mode)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/broadlink.py", line 299, in set_operation_mode
    self.send_ir()
  File "/config/custom_components/climate/broadlink.py", line 163, in send_ir
    command = self._commands_ini.get(section, value)
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'false'
```

This was the card:

![image](https://user-images.githubusercontent.com/25224882/41688429-7d9410c6-74c2-11e8-986f-6176c35ba06c.png)

The climate:

![image](https://user-images.githubusercontent.com/25224882/41688438-88850472-74c2-11e8-9e6d-5cc2ec877628.png)

And the operation mode was blank:

![image](https://user-images.githubusercontent.com/25224882/41688455-9362421a-74c2-11e8-96eb-959b387bca61.png)

Then setting the off command with quotes did the trick!

So this worked:

```
- platform: broadlink
  name: Ar condicionado da sala
  host: 192.168.1.34
  mac: 'B4:43:0D:F0:A1:A1'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001700b20
  default_operation: 'off'
  default_fan_mode: mid
  customize:
    operations:
      - 'off'
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

```

Now it is completely synced with my iOS app, works like a charm!

Thanks again my friend!

Cheers!
