### ISSUE TITLE
Turn off command

### ISSUE THREAD

**Issue by tatunts** [vpnmaster/homeassistant-custom-components#59]
Hello again! hehe

Sorry to bother (again) but maybe you could help me and clarify how this works: If I switch the group card toggle to "off", to turn off all devices on that group, and there is a climate entity, using your custom component, I get this error:

```
Log Details (ERROR)
Wed Jun 20 2018 20:12:33 GMT-0300 (Horário Padrão de Brasília)

Error executing service <ServiceCall climate.turn_off: entity_id=['climate.ar_condicionado_do_quarto']>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 440, in async_on_off_service
    await climate.async_turn_off()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 770, in turn_off
    raise NotImplementedError()
NotImplementedError
```

This is very useful to turn everything off on the group, in my case, an entire room...

![image](https://user-images.githubusercontent.com/25224882/41689496-3815cf80-74c7-11e8-9aa6-728cf2d8a537.png)

Is this related to your custom component or a default behavior for climate instances?

I believe there is a "turn_off" service to call for climate components...

Thanks!

**Comment by mitnits** [comment]
This can be trivially implemented by adding a method like this in custom_components/climate/broadlink.py

    def turn_off(self):
        """Turn off."""
        self._current_operation = 'off'
        self.send_ir()
        self.schedule_update_ha_state()

Checked it on my broadlink.py and it works fine. What I'd like to see is support for "On" - where the previous state would be restored (Cool or Heat, temperature, fan).

**Comment by Thunderbird2086** [comment]
![img_2733](https://user-images.githubusercontent.com/37539914/43946268-b7ec9c1e-9cbf-11e8-8305-a60c27a5a459.PNG)
I did almost same thing as @mitnits did.

**Comment by mitnits** [comment]
Looking at the code, I don’t think Off should be a mode of the ac, the
smodes should be Heat/Cool/Auto (and maybe Idle), but on/off should be
supported via SUPPORT_ON_OFF flag and just off the ac or turn it on
restoring the last mode it was using.
