### ISSUE TITLE
Changing target temperature but Unresponsive

### ISSUE THREAD

**Issue by ramith123** [vpnmaster/homeassistant-custom-components#6]
Here is the code I have.
climate:
  - platform: broadlink
    name: AC
    host: 192.168.86.213
    mac: '34:ea:34:e3:b8:e6'
    ircodes_ini: 'broadlink_climate_codes/toyotomi_akira.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    default_operation: cool
    default_fan_mode: auto
    customize:
      operations:
        - cool
      fan_modes:
        - low
        - mid
        - high
        - auto

I'm new here. I just recently started using home assistant. My issue is that when I changed the temperature from UI it doesn't send command to my RM 3 mini. It stays in one temperature. But when I changed the modes It sends the command but reset the temperature to target_temp: 20 from the config. I'm using a copy of toyotomi_akira.ini because it works with my ac. IDK what's going on

**Comment by ramith123** [comment]
I can set my temperature using the service just fine.

**Comment by vpnmaster** [comment]
Hello,
Versions 0.57.0 and 0.57.1 have a known bug in climate components. Please update to 0.57.2

**Comment by ramith123** [comment]
I'll see if this fixes it

**Comment by ramith123** [comment]
Awesome. It works. THANK YOU SO MUCH!!
