### ISSUE TITLE
Can not be controlled from Google Assistant

### ISSUE THREAD

**Issue by micro3x** [vpnmaster/homeassistant-custom-components#63]
Cool Components!!!  
I used your broadlink_climate control for my Hitachi AC and it Works Great except when integrated with google assistant, operational mode cannot be changed.
I was able to control the temperature and switch to heat and cool but only if the device is On.
If the Device is off (in IDLE state) I could not turn it on again via GA (Google Assistant).
So I looked around your code and the Hass.io GA component 
[here is the link](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/google_assistant/trait.py) and I figured out that GA Does not understand IDLE as an operational Mode. 
So long story - short, I included the STATE_OFF and added it to the DEFAULT_OPERATION_LIST and voila! works with GA.
I'm not exactly sure why are you using the IDLE state instead of the OFF!?!?
I have not tested this fix very well but if it checks out I'll create a pull request.

**Comment by vpnmaster** [comment]
The problem was that home bridge didn’t support off mode but only idle and home bridge was there before HA cloud integration. 
Now that native HomeKit supports only the off command I think that idle could gone.

**Comment by cubilon** [comment]
guys, anyone can explain what I'm doing wrong? Google Home says that what I ask is not available for my Mitsubishi A/C, but it works great on Home Assistant.

**Comment by micro3x** [comment]
I've created a pull request addressing this issue.
Google Home & Google Assistant are working in similar way and the issue is with the IDLE state.
I guess that in your Google Assistant you have added both your Hass.io and Broadlink accounts.
In this case your GA is able to set the temperature via broadlink cloud and not via Hass.io.
But in your GH you have only Hass.io and it's not working.

**Comment by vpnmaster** [comment]
Thank you for the PR.
I'm not using GH to test it. I hope works well.
