### ISSUE TITLE
Power consumption entity error

### ISSUE THREAD

**Issue by atomicpapa** [vpnmaster/homeassistant-custom-components#64]
Running Hass.io .72 on Ubuntu Server 18.04

config:
```
  - platform: broadlink
    name: Master Bedroom TV
    host: 192.168.1.14
    mac: '34:EA:34:XX:XX:XX'
    ircodes_ini: 'broadlink_media_codes/element.ini'
    ping_host: 192.168.1.18
```

Getting error...
`Invalid config for [media_player.broadlink]: string value is None for dictionary value @ data['power_consumption_entity']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/media_player.broadlink/`

**Comment by vpnmaster** [comment]
I'm using the exact same config in 0.72.1 and I cannot reproduce the error
