### ISSUE TITLE
Feature Request: insert "wait" command into combined commands

### ISSUE THREAD

**Issue by 9runner** [vpnmaster/homeassistant-custom-components#84]
Hello,

Since I use your media-player component to operate my several AV entertainment devices, including TV, set-top box and AV center, it works great! But I get a problem while operating my set-top box, one of its function need around half second wait before next ir code send out. Yes, I find I can insert many "|" between two ir code, but it's not so perfect since it is too short for every "|", some time I need to and 20 or even 40 "|" to make enough wait time. So could you add a "wait" function in your component?

**Comment by vpnmaster** [comment]
Added a 0.5s delay between combined commands. Please update only when HA 0.84 is available.
