### ISSUE TITLE
Feature suggestion: fan mode

### ISSUE THREAD

**Issue by adrianmihalko** [vpnmaster/homeassistant-custom-components#85]
Many AC's have fan mode, can you add this function to the IR climate component?

My AC has FAN mode: LOW/MID/HIGH.

Another feature suggestion is blade position support. It would be great to add this function to change blade position if it's available (low, mid, up, auto).

One more question: In dry mode I have only "auto" option. I can't control temperature, or any other option in this mode.

What should I do? One workaround is in my mind: add same command for all option (mid_xx, high_xx, low_xx, auto_xx)?!

**Comment by Thunderbird2086** [comment]
#75 has what you want. Please check.

**Comment by juancarloscastro75** [comment]
Hi, 

I have a LG air , and it has a fan mode. But using your IR codes and custom_component, it does not show.
For the rest it works great.

Regards
