### ISSUE TITLE
target_temp_step ignored in HomeKit

### ISSUE THREAD

**Issue by teejay-87** [vpnmaster/homeassistant-custom-components#88]
Not sure this is your component fault but HomeKit is ignoring the target_temp_step param.

**Comment by FezVrasta** [comment]
Same happens with Google Home, it allows me to set decimals on the climate component even if the step defaults to 1

**Comment by callifo** [comment]
Same issue with this last release. Previous build downloaded on 14 Dec 18 works as expected. I can now see errors showing Google Home sending values with fractions.

    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'mid_27.5251' in section: 'cool'

**Comment by tatunts** [comment]
Hello @callifo, how are you sir?

I am having problems also using HomeKit to set temperatures. When I send values with decimals, nothing happens, only without it.

Which version are you using that fixes this problem?

Thanks!

**Comment by tatunts** [comment]
Hello @vpnmaster! How is everything sir?

Sorry to bother you, but I am receiving this error when a temperature is set on the Home app:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'low_22.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 291, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 574, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/broadlink.py", line 285, in set_temperature
    self.send_ir()
  File "/config/custom_components/climate/broadlink.py", line 168, in send_ir
    command = self._commands_ini.get(section, value)
  File "/usr/local/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'low_22.5' in section: 'cool'
```

I believe it is the same problem as @callifo have.

Do you think it is possible to "round" this commands so a key can be found on the ini?

Thanks!

**Comment by callifo** [comment]
That's what needs to be done, but I can't see where this 'target_temp_step' is actually used. I would guess its not yet implemented.

It looks like the issue started as the variable types were changed from int to floats.

**Comment by callifo** [comment]
@tatunts This is the version I am using, it is just before the decimal support was added
https://github.com/vpnmaster/homeassistant-custom-components/blob/8ee711ff2d84116552d040e3a83ba4768f785e0d/custom_components/climate/broadlink.py

**Comment by vpnmaster** [comment]
Hello guys,
I’m trying to resolve this issue. Alexa have also the same behavior (step .5) but returns to the previous state. Of course, it throws an error to logs. What is the behavior of GA and HomeKit?

**Comment by tatunts** [comment]
>Hello guys, ...

@vpnmaster hello! Using HomeKit app on iOS nothing happens on Home Assistant, the current temperature does not change and no command is sent over BroadLink. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpnmaster** [comment]
@callifo The problem you describe resolved in the latest version

**Comment by callifo** [comment]
@vpnmaster  Thanks, tested and working again.
