### ISSUE TITLE
Please add tracker.json for custom_updater

### ISSUE THREAD

**Issue by hoangtuit** [vpnmaster/homeassistant-custom-components#89]
The [custom_updater](https://github.com/custom-components/custom_updater) component allows an easy management of all custom components and cards within home assistant.
It would be great if you could add a tracker.json file to allow easy updates of your component.

**Comment by nicx** [comment]
+1

**Comment by jokerigno** [comment]
+1

**Comment by Bellavista** [comment]
i'm novel hobbist. It would be great if you could add a tracker.json file.

**Comment by juancarloscastro75** [comment]
+1

**Comment by vpnmaster** [comment]
Added
