### ISSUE TITLE
FEATURE REQ: Sleep Timer (customise option)

### ISSUE THREAD

**Issue by talondnb** [vpnmaster/homeassistant-custom-components#97]
It would be great to add this an an optional customisation within the component. My LG split system has a sleep button I use regularly which allows a 1-7 hour sleep timer depending on how many times you press it. Having an additional dropdown item with these selections in the component would come in super handy. :)

**Comment by tyjtyj** [comment]
this should be down via input number. repeat the script until the number of hour reached .This does not seems to be part of climate.
